on:
  pull_request:
    types: [opened, closed, synchronize, reopened]
    branches: [ main ]
    
  - name: Create review app
        uses: CleverCloud/clever-cloud-review-app@v2.0.2
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.ORGA_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          type: 'node'
          flavor: 'XS'
          build-flavor: 'XS'

