name: Review App Deployment

on:
  pull_request:
    types: [opened, closed, synchronize, reopened]
    branches: [ main ]

jobs:
  deploy:    
    name: Deploy/redeploy review app
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Create review app
        uses: CleverCloud/clever-cloud-review-app@v2.0.2
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.ORGA_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          type: 'node'
          flavor: 'XS'
          build-flavor: 'XS'